name = "DiffEqFinancial"
uuid = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "2.8.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"

[compat]
AllocCheck = "0.2"
DiffEqBase = "6"
DiffEqNoiseProcess = "3, 4.1, 5.0"
Distributions = "0.25.100"
ExplicitImports = "1.14.0"
JET = "0.9, 0.10, 0.11"
RandomNumbers = "1"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "StochasticDiffEq", "Distributions", "JET", "AllocCheck", "ExplicitImports"]
