name = "DiffEqFinancial"
uuid = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "2.9.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"

[compat]
DiffEqBase = "6"
DiffEqNoiseProcess = "5"
Distributions = "0.25.100"
RandomNumbers = "1"
StochasticDiffEq = "6.28"
julia = "1.10"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "StochasticDiffEq", "Distributions", "Pkg"]
