[deps]
DiffEqFinancial = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[sources]
DiffEqFinancial = {path = "/home/runner/work/DiffEqFinancial.jl/DiffEqFinancial.jl"}

[compat]
DiffEqFinancial = "2.4.0"
Documenter = "0.27"
